name: Build Desktop

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact: linux

          - os: windows-latest
            artifact: windows

          - os: macos-latest
            artifact: macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
      
      - run: bun install --frozen-lockfile
      
      - run: bunx neu update
        working-directory: neutralino
      
      - run: bun run build:desktop
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: neutralino/dist/
